### ISSUE TITLE
Apparent regression from 0.19 to 0.20

### ISSUE THREAD

**Issue by Annakan** [emory-libraries/eulexistdb#10]
Since migrating to 0.20 we have the following message : 
`<bound method ExistDBException.message of ExistDBException('<html>\n<head>\n<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>\n<title>Error 405 La m\xe9thode HTTP GET n\'\'est pas support\xe9e par cette URL</title>\n</head>\n<body><h2>HTTP ERROR 405</h2>\n<p>Problem accessing /exist/xmlrpc/rest/db/. Reason:\n<pre>    La m\xe9thode HTTP GET n\'\'est pas support\xe9e par cette URL</pre></p><hr /><i><small>Powered by Jetty://</small></i><br/>                                                \n<br/>                                                \n<br/>                                                \n<br/>                                                \n<br/>                                                \n<br/>                                                \n<br/>                                                \n<br/>                                                \n<br/>                                                \n<br/>                                                \n<br/>                                                \n<br/>                                                \n<br/>                                                \n<br/>                                                \n<br/>                                                \n<br/>                                                \n<br/>                                                \n<br/>                                                \n<br/>                                                \n<br/>                                                \n\n</body>\n</html>\n',)>
`
Reverting to 0.19 correct the issue.
I had no time to dig into it and see if it is the interaction with our code and one of the new functionnality in eulexistdb, but before digging further is this something that you are already aware of ?

Did "base url" handling evolve recently ?
We currently have  http://user:password@hostname:port/exist/xmlrpc

ps: 
 

> La m\xe9thode HTTP GET n\'\'est pas support\xe9e par cette URL

Means 

> the GET method is not supported by this URL (405)  ;)

**Comment by rlskoeser** [comment]
@Annakan you're right.  I think the syntax for the base url has changed becaused I added some REST API functionality, but I see now that I failed to update the documentation to reflect that. :-(   And I also should have called it out in the change log as a backwards incompatible change.

I think in the new version the base url should be specified without the xmlrpc extension, and the username and password should be specified as parameters rather than in the connection string.    You can see the new parameters here: https://github.com/emory-libraries/eulexistdb/blob/master/eulexistdb/db.py#L144

Would it be helpful to add a check for the previous format of base url and handle it accordingly?  That probably wouldn't be too hard to add.

**Comment by Annakan** [comment]
Thanks for the prompt answer, It was my lucky "male hunch" day and I immediately  suspected something with the library and set my buildout to the previous version and zeroed in on that upgrade problem, so not much time lost and I probably do more mistake in a day than you in a year, trust me on this. 

There is an "deprecation mechanism" built into python : [DeprecationWarning](http://www.arruda.blog.br/programacao/python-use-warnings/) and [deprecationwarning gothcas](http://blog.zsoldosp.eu/2016/02/01/warnings-warn-some-deprecationwarning-gotchas/) but it is not perfect yet.
The "right" thing to do would probably be to accept both syntaxs for 2 versions with a warning/info on the logs before moving on but I must say I am quite fond of the one liner syntax. Reading 3 infos from my config file just to pass them to 3 parameters for the sake of aesthetics if tiring my poor fingers already.
I know "password URL" are dead for a long time on the web for security reasons but that is not the same case here since we are talking between trusted hosts, SSL to the rescue is over insecure channels..
Maybe you could support both syntax unless I missed something about the benefits of separating, URL and auth data  .

Whatever your choice is, this is no big deal as long as it is documented indeed, maybe with a nice exception if user/password **is not** provided in the params **but is** in the URL (password-less access to existdb API is legal right ? )  ;)

Thanks a lot for the time and effort you put on this project.

**Comment by rlskoeser** [comment]
Thanks for the input.  I've added support for the old syntax (keying on the presence of `xmlrpc` in the url) and it will be in the next release.  I also updated the documentation and the change log to make both changes clearer.

I think the main motivation for splitting these fields out was probably on the django side, because django can suppress sensitive configurations when in generates debug output and stack traces, but a password as part of a url is hard to flag as sensitive.
